# Generated by Django 2.0.7 on 2018-07-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20180716_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed Date'),
        ),
    ]
